### PR TITLE
BaSD/MS-001: setup npm and express server

### PR DESCRIPTION
**Pull request by ignacioaristo**
After pulling this branch, in your console type:

`npm install`

For install all the dependencies. (express, nodemon)

### CODE REVIEW

**Review by ravegliamartin — COMMENTED** [review]
It seems perfect to me!

**Review by leimeter-joaquin — APPROVED** [review]
Aprobado. Lamentablemente borró el console.log("hi"). Eso le daba carácter al código.

**Comment by ignacioaristo** [comment]
Remember: "npm run start" to run the app

**Comment by estefrare** [comment]
@ignacioaristo we should add this step in the readme

**Comment by ripellizzari** [comment]
Perfect!! I can't find the option to approve

**Pull request merged**
